version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.local
    depends_on:
      - postgres
      - redis
    networks:
      - ovela-network

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ovela_db
      POSTGRES_USER: ovela_user
      POSTGRES_PASSWORD: ovela_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./supabase/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./supabase/migrations:/docker-entrypoint-initdb.d/migrations
    networks:
      - ovela-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ovela-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - ovela-network

volumes:
  postgres_data:
  redis_data:

networks:
  ovela-network:
    driver: bridge